<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(string $search, User $user) {
        $qb = $this->createQueryBuilder('i');

        return $qb->where('i.name LIKE :search')
            ->andWhere('i.user = :user')
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('user', $user)
            ->getQuery()->getResult();

    }
}
