<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(string $search) {
        $qb = $this->createQueryBuilder('i');

        return $qb->where('i.name LIKE :search')
            ->setParameter('search', '%'.$search.'%')
            ->getQuery()->getResult();

    }
}
