# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    mediator:
        class: AppBundle\Mediator\Mediator
        autowire: true

    item_service:
        class: AppBundle\Service\ItemService
        autowire: true

    user_service:
        class: AppBundle\Service\UserService
        autowire: true

    category_service:
        class: AppBundle\Service\CategoryService
        autowire: true

    serialize_service:
        class: AppBundle\Service\SerializeService
        autowire: true

